[book]
authors = ["Oriol Gómez Díaz"]
language = "ca"
src = "src"
title = "Digitalització Aplicada als Sectors Productius"

[output.html]
git-repository-url = "https://github.com/oriolgomezdiaz/oriolgomezdiaz.github.io"